/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as cryptoDevsDaoSol from "./CryptoDevsDAO.sol";
export type { cryptoDevsDaoSol };
export type { CryptoDevsNFT } from "./CryptoDevsNFT";
export type { NFTMarketplace } from "./NFTMarketplace";
